// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBs0Dx_q0BisEN65mJnd1TMuWrZQkjta8',
    appId: '1:364192438806:web:573f55b7def8c201b4f337',
    messagingSenderId: '364192438806',
    projectId: 'vla-capstone',
    authDomain: 'vla-capstone.firebaseapp.com',
    databaseURL: 'https://vla-capstone-default-rtdb.firebaseio.com',
    storageBucket: 'vla-capstone.firebasestorage.app',
    measurementId: 'G-SNNYC1DRN6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6ophfxm2xpB87ugsU1uvCGQ0hcgqeJO8',
    appId: '1:364192438806:android:b5a215c58106dbbfb4f337',
    messagingSenderId: '364192438806',
    projectId: 'vla-capstone',
    databaseURL: 'https://vla-capstone-default-rtdb.firebaseio.com',
    storageBucket: 'vla-capstone.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvicnMwW552RLRFhAiBirbtL9Z694-AA8',
    appId: '1:364192438806:ios:8ba4e655373ae8dcb4f337',
    messagingSenderId: '364192438806',
    projectId: 'vla-capstone',
    databaseURL: 'https://vla-capstone-default-rtdb.firebaseio.com',
    storageBucket: 'vla-capstone.firebasestorage.app',
    iosBundleId: 'com.example.application',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvicnMwW552RLRFhAiBirbtL9Z694-AA8',
    appId: '1:364192438806:ios:8ba4e655373ae8dcb4f337',
    messagingSenderId: '364192438806',
    projectId: 'vla-capstone',
    databaseURL: 'https://vla-capstone-default-rtdb.firebaseio.com',
    storageBucket: 'vla-capstone.firebasestorage.app',
    iosBundleId: 'com.example.application',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBs0Dx_q0BisEN65mJnd1TMuWrZQkjta8',
    appId: '1:364192438806:web:11d5e8129d7d3728b4f337',
    messagingSenderId: '364192438806',
    projectId: 'vla-capstone',
    authDomain: 'vla-capstone.firebaseapp.com',
    databaseURL: 'https://vla-capstone-default-rtdb.firebaseio.com',
    storageBucket: 'vla-capstone.firebasestorage.app',
    measurementId: 'G-XCY8H7E7QH',
  );
}
